
import commands
OS = commands.getoutput('uname')
if ('CYGWIN' in OS): OS='Cygwin'

CCFLAGS = ['-DFLAT_GUI']
LIBS=['SDL'],
LIBPATH=[]
CPPPATH=[]

if 'debug' in ARGUMENTS:
	CCFLAGS += ['-g','-ggdb']
else:
	CCFLAGS += ['-O3']

if OS=='Cygwin':
	CCFLAGS += ['-DCYGWIN','-DWIN32','-mno-cygwin']
if OS=='Darwin' or OS=='Cygwin':
	LIBPATH += ['../libdeps/SDL-1.2.11/build/.libs']
	CPPPATH += ['../libdeps/SDL-1.2.11/include']

if OS=='Linux':
	CPPPATH += ['/usr/include/SDL']

StaticLibrary('scrobui', ['scrobui.cpp', 'toolkit.cpp', 'dotum10.cpp'],
			  LIBS=LIBS, LIBPATH=LIBPATH, CPPPATH=CPPPATH, CCFLAGS=CCFLAGS)
