
CCFLAGS = ''

if 'debug' in ARGUMENTS:
	CCFLAGS =+ '-g -ggdb '

#CCFLAGS += '-DFLAT_GUI -DWIN32 -DCYGWIN'
CCFLAGS += '-DFLAT_GUI -DCYGWIN'

StaticLibrary('scrobui', ['scrobui.cpp', 'toolkit.cpp', 'dotum10.cpp'],
			  LIBS=['SDL'],
			  CCFLAGS=CCFLAGS)
